// LOCALHOST 
### Get all the paints
GET http://localhost:8080/paint


### Get all the home improvement DIYs
GET http://localhost:8080/homeImprove

### Create Contact 
POST http://localhost:8080/homeImprove HTTP/1.1
Content-Type: application/json

{
    "item": "table",
    " estimatedCost ": " $150.00 ",
    "tiannaPriority": 4,
    "toddPriority": 2,
    "totalPriority": 6,
    "store": "Ikea",
    "room": "Guest",
    "transportation": "truck"
}

### Delete HomeImprove 

DELETE http://localhost:8080/homeImprove/644ff8bbb5da983863f5be5e HTTP/1.1


// PRODUCTION Deploy  
### Get all the paints
GET https://homeprojects.onrender.com/paint

### Get all home improvement DIYs
POST https://homeprojects.onrender.com/homeImprove HTTP/1.1
Content-Type: application/json

{
    "item": "table",
    " estimatedCost ": " $150.00 ",
    "tiannaPriority": 4,
    "toddPriority": 2,
    "totalPriority": 6,
    "store": "Ikea",
    "room": "Guest",
    "transportation": "truck"
}
